apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "operator.labels" . | nindent 4 }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "operator.fullname" . }}-manager-role
  labels:
    {{- include "operator.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: [configmaps, serviceaccounts]
  verbs: [create, delete, get, list, patch, update, watch]
- apiGroups: [""]
  resources: [namespaces, nodes, pods]
  verbs: [get, list, watch]
- apiGroups: [apps]
  resources: [daemonsets]
  verbs: [create, delete, get, list, patch, update, watch]
- apiGroups: [apps]
  resources: [replicasets]
  verbs: [get, list, watch]
- apiGroups: [rancheraudit.io]
  resources: [auditlogconfigs]
  verbs: [create, delete, get, list, patch, update, watch]
- apiGroups: [rancheraudit.io]
  resources: [auditlogconfigs/finalizers]
  verbs: [update]
- apiGroups: [rancheraudit.io]
  resources: [auditlogconfigs/status]
  verbs: [get, patch, update]
- apiGroups: [rbac.authorization.k8s.io]
  resources: [clusterroles, clusterrolebindings]
  verbs: [create, delete, get, list, patch, update, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "operator.fullname" . }}-manager-rolebinding
  labels:
    {{- include "operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "operator.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "operator.fullname" . }}-leader-election
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "operator.labels" . | nindent 4 }}
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: [leases]
  verbs: [create, get, list, update, watch]
- apiGroups: [""]
  resources: [events]
  verbs: [create, patch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "operator.fullname" . }}-leader-election
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "operator.fullname" . }}-leader-election
subjects:
- kind: ServiceAccount
  name: {{ include "operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
