apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: auditlog-operator-role
rules:
  - apiGroups: ["rancheraudit.io"]
    resources: ["auditlogconfigs", "auditlogconfigs/status", "auditlogconfigs/finalizers"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["core"]
    resources: ["configmaps", "secrets", "serviceaccounts"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
